tos_path = "/balun/tos"
privacy_path = "/balun/privacy"
database_path = "database.sqlite"
path = "config.toml"

[discord]
guild_ids = [1234567890,9876543210]
token = ""
client_id = ""
perm_int = 326484716608
scope = "bot%20applications.commands"

[webserver]
listen_address = "127.0.0.1"
listen_port = 8686

[interaction]
owner = 1234567890
