tos_path = "/balun/tos"
privacy_path = "/balun/privacy"

[discord]
guild_id = ""
token = ""
client_id = ""
perm_int = 326417542208
scope = "bot%20applications.commands"

[webserver]
listen_address = "127.0.0.1"
listen_port = 8686

[interaction]
operators = [1234567890, 9876543210]
